version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end-nextjs
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network: